### PR TITLE
Add a link to company's website

### PR DESCRIPTION
**Pull request by bastnic**
'cause I didn't knew it, and I like to know where to postulate (even if I wont, 'cause I love my job).

### CODE REVIEW

**Comment by totophe** [comment]
:+1:

**Comment by ploum** [comment]
Aha, this was more or less on purpose, just for not scaring good coders with the corporate website. But contribution accepted :-)

**Comment by bastnic** [comment]
They will anyway. Since when do you encourage obfuscation over transparency ;). (kidding).

**Comment by ploum** [comment]
Just to challenge people so they would defend transparency ;-)

**Pull request merged**
